### ISSUE TITLE
Anchored 'request callback' module / Contact module (always at top of page when scrolling)

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#10]
As a user
I want to be able to speak to a member of the Research Resource team if I am unsure about any of the information

As a user
I want to be able to get help if I am unable to complete actions on the website such as signing up or consenting

As a user, I want to be able to speak to a member of the Research Resource team without it costing me any money

**Comment by sarahwelton** [comment]
so that if I don't understand anything, I can get clarity, and therefore can make an informed decision as to whether I want to sign up or not

so that I can complete my registration

As a user, I want it to be quick and easy to find contact information so that I can get in touch with the team at the time I need their help or guidance.

**Comment by Cleop** [comment]
@ellemindwave In terms of functionality, if a user clicks on 'request callback' will this fire off an email to the RR team so they can return the call? How will they know which number to call if I've not yet completed the registration and therefore RR do not yet have my phone number?

**Comment by ellemindwave** [comment]
@Cleop @sarahwelton As far as I know, yes, it would fire off an email to the RR team so that they could call them back. 
Good question about the phone number - could a field to enter preferred phone number appear when you request the call back? @sarahwelton what do you think?

**Comment by sarahwelton** [comment]
<img width="246" alt="call-back-example" src="https://cloud.githubusercontent.com/assets/26305143/23990964/923fc38e-0a2f-11e7-820e-c895cc481c14.png">

**Comment by SimonLab** [comment]
The "request a call" block doesn't appear on the new wireframes. @ellemindwave @sarahwelton on which pages should this block should be displayed on?

**Comment by ellemindwave** [comment]
Hi @SimonLab , @sarahwelton can confirm this, but the 'Request a call' block will be anchored to the top of the pages that the team choose. Mainly on the 'About' page, 'FAQs' page, 'Consent' page, and 'Account' page, but it would be great to be able to have choice so that they can test which pages it is most useful on.

Is it possible for it to be built as a module that can be added to pages/taken off pages by the admin on the back-end? How much extra work would this require than just stating which pages it should be on?

**Comment by Cleop** [comment]
- Not yet anchored but otherwise functioning

**Comment by ellemindwave** [comment]
After discussion with client - this needs to be a 'Help' module that instead of just offering a call-back, is more like a one-stop contact module offering a phone number, email link and request callback feature, wrapped up in one.

**Comment by Cleop** [comment]
@ellemindwave can you be more explicit about what you mean by 'email link'? Do you just mean an email address that people can copy and paste and contact? or one that when they click on it will open up their mail programme? 

Please can we have an updated wireframe for this?

**Comment by Cleop** [comment]
@ellemindwave the new amendment for this module should be opened as a new issue because it's not a continuation of the original issue objective but a substantial change. Please can you create it separately?

**Comment by Cleop** [comment]
@ellemindwave please can we have an email address for the King's team that you want the callback email notifications to be sent to?

**Comment by ellemindwave** [comment]
@Cleop It will most likely be ttrr@kcl.ac.uk 

I will close this issue and open a new one for the new requirements for this module
