### ISSUE TITLE
Add link to log in on sign up form

### ISSUE THREAD

**Issue by sarahwelton** [research-resource/research_resource#104]
Need to add a link underneath / next to (see UI) the sign up module to say "Already signed up? Log in" with the "Log in" linking to the log in page.

**Comment by Danwhy** [comment]
We already have this link on the signup page, which is what was on the wireframes:
<img width="978" alt="screen shot 2017-03-29 at 13 02 49" src="https://cloud.githubusercontent.com/assets/8939909/24453535/33a80a6a-1480-11e7-97a9-de53b13f0abf.png">
Did you want it on the sign up forms on the other pages (Home etc) as well?

**Comment by sarahwelton** [comment]
Sorry, misunderstanding. I mean on the sign up module wherever it appears - somewhere it needs to have a text link to say "Already got an account? Log in here" - not JUST on the sign up page. Eg on the homepage. Hopefully this will become clearer once I've had a chance to update wireframes.

**Comment by sarahwelton** [comment]
<img width="1037" alt="screen shot 2017-04-02 at 16 44 11" src="https://cloud.githubusercontent.com/assets/26305143/24588628/a377c812-17c3-11e7-8d6b-54144f690c65.png">

**Comment by Danwhy** [comment]
Done in #135

**Comment by ellemindwave** [comment]
@Danwhy When I click on the 'Already have an account?' link underneath the 'Sign Up' button, it doesn't take me anywhere. Is it meant to direct me to the log-in page, the same way the button in the top right hand corner of the homepage does?
![screen shot 2017-04-05 at 10 30 07](https://cloud.githubusercontent.com/assets/26304634/24699190/14155a2a-19eb-11e7-8a2d-b16439dc01ec.png)

**Comment by sarahwelton** [comment]
Yes exactly that - to the log in page.

**Comment by Danwhy** [comment]
Yes sorry, looks like I added the label a little prematurely! Should be working now

**Comment by ellemindwave** [comment]
👍  working fine now! thanks
