### ISSUE TITLE
About page should show in user journey before consent pages

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#106]
So that a user can find out everything they need to know before entering the consent process. 

The About page and the Information sheet are the same thing. 

Users must have read the About page before continuing to the consent process

**Comment by Cleop** [comment]
- Do the users need to click a checkbox to say that they've read the About page before proceeding or is it just part of the user journey?

So in terms of a user journey you start on the home page, click on 'sign up' and then enter your phone no/email, click submit and then go to the about page? At the bottom of which there is a button saying 'proceed to consent page' or 'proceed' or something?

Or do you arrive on the about page when you click 'sign up' and then click a button saying 'sign up'(?) at the bottom of the about page to continue?

Would be good to have more detail on this.

**Comment by ellemindwave** [comment]
@Cleop Thanks for this. 
There should be no checkbox to click, it will just be part of the user journey. 

The user sign-up journey should go as follows: 

Home page --> sign up by entering minimal information (name, email/phone no) --> click submit -->
Receive verification email --> Linked back to 'About' page -->  consent --> qualtrics ---> done (when saliva kit has been received back by the lab and manually recorded into Redcap)

**Comment by Cleop** [comment]
@ellemindwave did this this requirement come from user testing?

The sign up process is already long and adding another stage to it is likely to reduce the number of successful sign ups, especially given the length of the About page.

It's not to say that the idea might not be of use to users if testing were to show that they felt a lack of info before signing up. However agile methodologies would promote starting simply (without this) and then iterating where user testing shows the need to.

**Comment by ellemindwave** [comment]
@Cleop Unfortunately, from an ethics point of view, the user must have read the about page before continuing with the sign-up process. I agree that it is a long page, but it has to be this way I'm afraid

**Comment by ellemindwave** [comment]
@SimonLab @Cleop Thanks guys, closing this issue
