### ISSUE TITLE
Confirming dynamic vs static content

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#110]
I just wanted to outline and make sure everyone has the same understanding for what content on RR will be dynamically generated from Redcap and what will be hard coded (and need changing in the code to edit):

**Dynamic**:
- Project info
- Consent info 

**Static**:
- Team / Who page #94 
- About 
- FAQs #93 
- Ts & Cs #95 

The reason for this is that these distinctions are what the current time estimates are based on and if any of this is inaccurate then the time estimates need to be changed accordingly.

Please let me know @ellemindwave and @sarahwelton if any of this isn't inline with your understanding.

**Comment by ellemindwave** [comment]
@Cleop @sarahwelton 
The dynamic pages are correct in terms of being the ones that get content generated by Redcap.

Will the static pages be content manageable for the client? 
The content on them is static, but it is probably quite likely than a FAQ or T&C changes from time to time, or a team member leaves etc how would they be able to go on and update it?

**Comment by Cleop** [comment]
@ellemindwave, re: your question on static pages. As it stands, these pages would need changing in the code if the content changed but I created this issue to make sure that this was clear. At the moment, following the discussion raised in issue #69 there will not be a CMS.

**Comment by Cleop** [comment]
@ellemindwave Can you confirm that you're happy with what I've outlined regarding static content and no CMS?

If you are then please can you close the old issues relating to a CMS and admin/super admin functionality? They are listed in #69

**Comment by sarahwelton** [comment]
Hi @Cleop - for now, yes, that will have to be the case. 

Could we pick this up separately to talk about CMS and time implications? Half for my reference generally (future projects with DWYL etc!) and half so that we can be more informed when talking about this to the client for this project as to why they are unable to make any changes without going through the development team. Not sure where to note this request! Slack?

**Comment by ellemindwave** [comment]
@Cleop Thanks - closing this issue 👍
