### ISSUE TITLE
Create Unique Project Consent pages

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#116]
@ellemindwave @sarahwelton will each project require its own consent page for the unique terms of that project? Or can a user simply join a project by clicking a button on the project page with no further action required?

If so, please can we have a wireframe?

**Comment by ellemindwave** [comment]
@Cleop Each project will have its own consent page with unique terms of that project that the user will consent to.

This relates to issue #119 in that the consent fields for each project can be dynamically pulled through from Redcap too?

@sarahwelton

**Comment by Cleop** [comment]
@Danwhy @SimonLab can you confirm for @ellemindwave regarding Redcap and project-specific consent pages?

**Comment by Cleop** [comment]
@ellemindwave Please can you add a priority label to this? I imagine it's quite important considering without it, no users will be able to sign up for projects?

**Comment by Cleop** [comment]
@ellemindwave, I've checked with the team and I can confirm that individual project consent fields can be dynamically pulled in from Redcap.

**Comment by ellemindwave** [comment]
@Cleop Great, so then each project should have its own consent page. What do you need in order to proceed with this issue? 
The project consent pages will look just like the TTRR consent page in terms of functionality and style
@sarahwelton

**Comment by Cleop** [comment]
Thanks @ellemindwave, the only thing remaining to wait for will be content. We can use filler for the time being.

**Comment by ellemindwave** [comment]
Placeholder content will be provided in a separate issue
