### ISSUE TITLE
Create Individual Project Pages

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#118]
**As a** user...
**I want to** be able to read the full details about a project...
**so that** I am well informed to decide if I want to partake in it or not.

- Create a page for each individual project (awaiting wireframe and UI)
- The page will dynamically generate the project info listed on Redcap

Until we have the wireframes, the project pages will just list out the content from Redcap without styling and will be subject to change later.

@ellemindwave @sarahwelton it would be great to have the wireframes asap 😄

**Comment by SimonLab** [comment]
see #133 
This page is going to look similar to the consent page.
-  [x] get data from redcap for a particular project
- [x] display data on /projects/show endpoint
