### ISSUE TITLE
Email Notification of successful initial sign-up

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#12]
As a user, I want confirmation that I have successfully initially signed up so that I can proceed to complete my registration.

There was talk on whether or not this would have to be a confirmation email due to the sensitive nature of the data that will be provided by the user. 

Currently the user would enter their initial sign up details (name, email, phone number) and then be sent a confirmation email. The link in this confirmation email would direct them straight back to the site and into the next relevant stage in their sign-up journey (the consent section)

**Comment by Cleop** [comment]
@ellemindwave 'confirmation email' clarification?

**Comment by ellemindwave** [comment]
Closing this issue as it is a duplicate of #103
