### ISSUE TITLE
Merge consent pages 

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#123]
The TTRR consent page and the BioResource page are now just going to be contained within the same consent page, and will include the functionality to request a saliva sample kit issue #18 and #124

**Comment by Cleop** [comment]
Referred to at the end of #13

**Comment by Cleop** [comment]
- Awaiting new wireframes/ content

**Comment by sarahwelton** [comment]
Content is still being finished up by the client. 

In the mean time - hope this helps 

![consent__1_](https://cloud.githubusercontent.com/assets/26305143/24588422/955dc26c-17bf-11e7-9d49-293182d302f7.png)

**Comment by iteles** [comment]
@sarahwelton The image didn't finish uploading here :blush:

**Comment by sarahwelton** [comment]
NB theres a little error on that page - item 6 should also have "Yes / No" radio buttons!

**Comment by ellemindwave** [comment]
👍
