### ISSUE TITLE
Resources page

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#125]
As a user, I want to be able to access relevant links and information about mental health, so that I feel informed and supported

This would link from the footer ( Members' Resources ), and the content for this page is below. 

Wireframe needed from @sarahwelton

**Comment by ellemindwave** [comment]
**The Members’ Resource**

Links to information sources
•	Southwark Talking Therapies: https://slam-iapt.nhs.uk/southwark/welcome-to-southwark-psychological-therapies-service/
•	Mind Lambeth and Southwark: http://lambethandsouthwarkmind.org.uk/
•	Mind Information and Support: http://mind.org.uk/information-support/

Upcoming local support groups
•	https://slam-iapt.nhs.uk/southwark/news-and-events/
•	Lambeth and Southwark peer support group: http://lambethandsouthwarkmind.org.uk/how-we-can-help-you/peer-support/

Online therapy resources
•	https://slam-iapt.nhs.uk/southwark/welcome-to-southwark-psychological-therapies-service/resources/

Understanding Anxiety
•	https://slam-iapt.nhs.uk/problems-we-help-with/anxiety/

Understanding Depression
•	https://slam-iapt.nhs.uk/problems-we-help-with/depression/

Understanding Panic
•	https://slam-iapt.nhs.uk/problems-we-help-with/panic/

**Comment by Cleop** [comment]
@ellemindwave is the term 'Member' referring to users of RR or members of the various NHS localities involved?

If it refers to RR members perhaps it would make more sense to only be visible when logged in?
Or if it's not just for RR members perhaps it would make sense being named something clearer like 'support materials' or 'external resources'?

**Comment by ellemindwave** [comment]
@Cleop I agree, the client wants it to be called Members' Resources, but it fit much better in the header just called 'Resources' so I will check with them.

I think the plan is for it to be available to users whether they are logged in or not, but again, I will double-check whether or not they have made up their minds on this, they hadn't on Tuesday

**Comment by ellemindwave** [comment]
@Cleop This page will just be called 'Resources' now, and is available to everyone, logged in or not 👍

**Comment by sarahwelton** [comment]
"Resources" might be a little confusing considering the whole site is called Research Resource...

Lets re-think.

**Comment by sarahwelton** [comment]
This is just a basic text page - so as per the about page without any of the additional modules. @Cleop / @iteles can you confirm whether you need a wireframe for this? Thanks!
