### ISSUE TITLE
Adding functionality to 'request callback' module to make it a 'help' module

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#128]
The existing 'request callback' module simply provides a way for the user to enter their phone number and request a call back. 

On reflection, the team have decided that they would like this anchored module to **also** contain:

Email link (that when clicked on, opens their mail browser)
Call us (details of a freephone number)
Link to the FAQ page

@sarahwelton will create a wireframe for this new version of the module

**Comment by sarahwelton** [comment]
<img width="383" alt="screen shot 2017-04-02 at 14 35 43" src="https://cloud.githubusercontent.com/assets/26305143/24587603/b46106f0-17b1-11e7-87e8-aa82d616d7a7.png">
