### ISSUE TITLE
Consent page (part 1 - Talking Therapies Research Resource consent)

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#13]
As a user
I want clear and comprehensive information about what my data can and will be used for so that I feel in control and informed.

**Comment by ellemindwave** [comment]
![screen shot 2017-03-17 at 15 00 06](https://cloud.githubusercontent.com/assets/26304634/24048982/84fa3896-0b22-11e7-9b25-fff62f7799ca.png)
![screen shot 2017-03-17 at 15 00 15](https://cloud.githubusercontent.com/assets/26304634/24048983/8513917e-0b22-11e7-8e8e-c96469e0c814.png)

**Comment by Danwhy** [comment]
Time estimate is for basic outline as shown above. This doesn't include dynamically pulling the fields from Redcap, which will have to be done later when we have the api access

**Comment by ghost** [comment]
Hi, sorry just need to clarify as I'm stepping in on this one... is this issue to pull through correct text for the consent questions rather than the lorem ipsom?  If so, it works!

**Comment by Cleop** [comment]
@sarahwelton we believe this one is ready to close as the page successfully retrieves the data from Redcap. However @katyedwards has asked for clarification due to being new to the project, so please review for us.

**Comment by sarahwelton** [comment]
Hi - a couple of things:

1) the phone number needs to be present on the notification when a user selects "no" on a consent item. 

2) some of the items are not mandatory. Items #6 and #7 are not mandatory - and potentially #5 but we will need clarification from the team. (I believe they are still in debates about this!)

**Comment by ellemindwave** [comment]
This should be merged with #15  - the two consent pages will now be one and the same, on one form with around 10 questions - content TBC

**Comment by Cleop** [comment]
Thanks @ellemindwave, I will close the other issue then as that page is yet to be created.

We will keep the content as it currently is until we are updated.

**Comment by Cleop** [comment]
@ellemindwave please can you create the merging of the consent pages as a new issue? The requirements are different from the original objective of this issue.

And then close this issue if the requirements have been met.
