### ISSUE TITLE
Content for Notification Email after initial sign up (before consent page)

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#130]
Relates #103 
- Content needed

**Comment by ellemindwave** [comment]
@Cleop Content from client for this email as follows:


Dear _____,
Thank you for signing up to the Talking Therapies Research Resource. 
Once you have completed an initial questionnaire, and decided if you are happy to provide a saliva sample, you will be able to sign up to our current projects. It is up to you how many you take part in.
For more information, please visit our FAQs page. If you still have any questions, you can contact the team by replying to this email, or on FREEPHONE 0800 955 199.
Kind regards,
The Talking Therapies Research Resource Team
