### ISSUE TITLE
Individual Projects Pages: content needed

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#133]
Need content for individual projects pages.

**Comment by SimonLab** [comment]
Having one example of a project data can help us to understand the full structure and data needed and will help us to validate our Redcap structure, see #119 . @Cleop do you know if the team have already some project examples that could be share with us?

**Comment by Cleop** [comment]
@ellemindwave @sarahwelton do we have an example project(s) that we can use?

**Comment by sarahwelton** [comment]
I think we're still waiting on content from the client. @ellemindwave is that right?

**Comment by ellemindwave** [comment]
@Cleop @SimonLab Here is some content to use for the example project. 

Links #118 

project name: **BioPoRT Project**

project description: **We want to identify psychological and genetics factors that predict response to psychological therapy and will help in identifying which treatments might work best for different people.**

I think I have added this into the correct issue, but apologies if not! :)
