### ISSUE TITLE
Alerts on Consent page 1 to advise that particular consent is necessary in order to proceed

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#14]
As a user
I want to be able to clearly see which things I **must** consent to to participate in the TTRR & the BioResource

As a user 
I want to be able to clearly see **why** certain consent is essential to participation to the TTRR & the BioResource

**Comment by ellemindwave** [comment]
![screen shot 2017-03-17 at 15 00 06](https://cloud.githubusercontent.com/assets/26304634/24049063/c599c768-0b22-11e7-9cbf-d7c327457a0f.png)
![screen shot 2017-03-17 at 15 00 15](https://cloud.githubusercontent.com/assets/26304634/24049064/c5a1a410-0b22-11e7-8ed2-e33e935e14cc.png)

**Comment by ghost** [comment]
Alerts work on all questions.  Thanks!
