### ISSUE TITLE
How should projects display on the projects page when there are >3 ?

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#140]
How should projects display on the projects page when then are more than 3?
This is how they currently look with just 3:
![image](https://cloud.githubusercontent.com/assets/16775804/24702222/c47d2fbe-19f5-11e7-82ed-fc9b87897fdf.png)

- Should extra ones display below?
- What if there are 10s or 100s of them? Will it look very messy?

@sarahwelton @ellemindwave @indiamindwave24

**Comment by indiamindwave24** [comment]
There is unlikely ever be 100s of projects but good question.

I am in discussion with @sarahwelton as to whether:

- We have a 'view all projects' button that takes you to a full page

- Or stack all below the first row?

We will let you know our decision ASAP :)

**Comment by iteles** [comment]
@indiamindwave24 If we're looking for a good short-term solution, your second option will be faster to implement 👍

**Comment by indiamindwave24** [comment]
go ahead with second option :) At least to begin with there will be very few projects
