### ISSUE TITLE
Project Epic

### ISSUE THREAD

**Issue by SimonLab** [research-resource/research_resource#141]
We have a few issues linked to the project feature:

- #25 UI of sections for projects, Current + Archived
- #26 See Archived project
- #32 List projects a logged in user has applied to
- #48 Send email to TTRR team when a user applies to a project
- #115 Display projects in sections: Applied and Archived
- #116 Each project has its own consent page
- #118 Individual page for each project
- #119 Redcap project structure + load dynamically content from Redcap for projects
- #133 Example content page for project
- #140 UI and how to display lists of projects when the number is > 3
- #142 How to define status for project in Redcap (current, archived)
- #154 Block consent project if primary consent not complete

**Comment by indiamindwave24** [comment]
@SimonLab @Danwhy <img width="1061" alt="screen shot 2017-04-11 at 5 24 51 pm" src="https://cloud.githubusercontent.com/assets/25007700/24919543/f8c0438e-1edb-11e7-97c7-f1ec89b30847.png">
The buttons here are not styled. One is sitting within the box and one is sitting outside the box.

**Comment by iteles** [comment]
Closing as all linked issues are closed 👍
