### ISSUE TITLE
Define in Redcap the projects sections (Current and Archived)

### ISSUE THREAD

**Issue by SimonLab** [research-resource/research_resource#142]
To dispatch the projects the TTRR team will have to define a property in Redcap "current" or "archived" which will automatically place the project on the right section.
- [x] Define the "status" field in Redcap where the TTRR team can update the status manually
- [x] Update the function which get the list of projects to also get the status or the projects

linked to #25

**Comment by SimonLab** [comment]
The status of the project is defined with the annotation on the status field in Redcap. If the value is "archived" the project is archived otherwise if the annotiation doesn't have any value or if the value is not "archived", the project is considered "current"

**Comment by ellemindwave** [comment]
@SimonLab 
Project Statuses
1.	Recruiting participants
2.	Data analysis
3.	Writing up results
4.	Published
5. Archived

**Comment by ellemindwave** [comment]
have added a new issue for the changing of the project statuses in Redcap, as the original issue has been fulfilled 👍
