### ISSUE TITLE
Travis and cached build folder

### ISSUE THREAD

**Issue by SimonLab** [research-resource/research_resource#159]
To speed up the tests on Travis we can cached some folders. Can we cache the build folder?
see #158

**Comment by samhstn** [comment]
I think it's the same thing as locally when you have the `_build` and `deps` folders "cached" and run `mix deps.get`, etc.

**Comment by Danwhy** [comment]
This guy recommends it: https://dockyard.com/blog/2015/12/02/speeding-up-elixir-project-build-times-on-travis-ci

We could try it by pushing a cached build, then write a test that should fail, push that and see if it fails on travis

**Comment by Danwhy** [comment]
So I pushed a failing test to the branch where travis had cached the build: 
<img width="942" alt="screen shot 2017-04-07 at 17 32 01" src="https://cloud.githubusercontent.com/assets/8939909/24809887/3a99084e-1bb8-11e7-8847-e23c24beb707.png">

It successfully failed! So the code is being updated just fine. It's also almost twice as fast as without caching:

<img width="939" alt="screen shot 2017-04-07 at 17 33 41" src="https://cloud.githubusercontent.com/assets/8939909/24809927/5ac0f406-1bb8-11e7-8468-1333b58f6bc7.png">
<img width="939" alt="screen shot 2017-04-07 at 17 32 07" src="https://cloud.githubusercontent.com/assets/8939909/24809933/5dee9fa2-1bb8-11e7-84ad-4273b9fc8a03.png">

So it definitely seems worth it to me. If we cache our dependencies I imagine it will be even faster.

**Comment by SimonLab** [comment]
Thanks for testing that @Danwhy , @shouston3 do you mind to reopen your PR?

**Comment by SimonLab** [comment]
Thanks @shouston3 and @Danwhy the tests are quick :+1:
