### ISSUE TITLE
Consent Page: Functionality for entering address for sending of saliva kit 

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#18]
As a user, I want to choose where my saliva kit is delivered to

- this will send an email / alert / somehow inform the TTRR team that a new saliva kit needs to be sent out. 

As far as we are aware at the moment, they will just need the name and address of the person

**Comment by Cleop** [comment]
@ellemindwave at what stage would you like the address to be taken? During the saliva consent form? or perhaps during the profile information form?

**Comment by ellemindwave** [comment]
@sarahwelton @Cleop We would like this to be within the Saliva consent form, as the address they want their saliva kit sent to may be different to the address that is in their profile (i.e. they could want it delivered to work etc)

**Comment by Cleop** [comment]
![image](https://cloud.githubusercontent.com/assets/16775804/24096037/c1e1b11c-0d57-11e7-9e31-c1b80e3895d1.png)
![image](https://cloud.githubusercontent.com/assets/16775804/24096052/cddb5e1e-0d57-11e7-9a26-e926b8170c7c.png)
![image](https://cloud.githubusercontent.com/assets/16775804/24096058/d8301814-0d57-11e7-886b-1edd2343cbfc.png)
![image](https://cloud.githubusercontent.com/assets/16775804/24096069/df9d6d7c-0d57-11e7-8ac9-f6f20d9b76ee.png)

**Comment by Cleop** [comment]
@sarahwelton @ellemindwave  where would you like the address part? Underneath the saliva request content where it currently says TBC?

**Comment by Cleop** [comment]
Renamed as there is now only one consent page.

**Comment by Cleop** [comment]
@ellemindwave please can we have an email address for the King's team that you want the callback email notifications to be sent to?

**Comment by Cleop** [comment]
New wireframe including address : 

![consent__1_](https://cloud.githubusercontent.com/assets/26305143/24588422/955dc26c-17bf-11e7-9d49-293182d302f7.png)

**Comment by ellemindwave** [comment]
@sarahwelton Please can you have a check of this too? 
Is the look-up address from the postcode functionality a lot more work?

**Comment by sarahwelton** [comment]
Sorry, my mistake. I didn't complete all the wireframes for this process. I'd meant it to be a postcode look-up which would then populate the address fields. Sorry I'd meant to post a link to an example. Will try and do this asap.

**Comment by ellemindwave** [comment]
Closing this issue, and will inform the client as to the need for the Royal Mail API for a postcode look-up
