### ISSUE TITLE
Team photos for who we are page

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#181]
Adding headshots of the team into the 'Who we are' page

**Comment by ellemindwave** [comment]
![gerome-breen3](https://cloud.githubusercontent.com/assets/26304634/24861844/14024786-1df2-11e7-9e6c-b06947335683.jpg)
![kate 1](https://cloud.githubusercontent.com/assets/26304634/24861845/14079f7e-1df2-11e7-8320-b7c7333f6487.jpg)
![kim 1](https://cloud.githubusercontent.com/assets/26304634/24861846/140c74f4-1df2-11e7-90da-09bd84ea7f4d.jpg)
![thalia](https://cloud.githubusercontent.com/assets/26304634/24861847/140f7136-1df2-11e7-95f8-c3e70c77139b.png)

**Comment by ellemindwave** [comment]
From top:

Gerome
Kate
Kim
Thalia

**Comment by ellemindwave** [comment]
@SimonLab  Some more photos have come through for this page, but they are on documents. Let me know if they aren't good enough and I'll go back to the client.

[Who we are example page Allan.docx](https://github.com/research-resource/research_resource/files/910746/Who.we.are.example.page.Allan.docx)
[Who we are example page Carmine 1.docx](https://github.com/research-resource/research_resource/files/910748/Who.we.are.example.page.Carmine.1.docx)
[Who we are example page Matthew 1.docx](https://github.com/research-resource/research_resource/files/910747/Who.we.are.example.page.Matthew.1.docx)
[Who we are example page Tony.docx](https://github.com/research-resource/research_resource/files/910749/Who.we.are.example.page.Tony.docx)

**Comment by SimonLab** [comment]
Thanks @ellemindwave the documents seems to have more links for some profiles, do these links should be displayed on the website too?

**Comment by ellemindwave** [comment]
@SimonLab Yes please - thanks for pointing that out!
