### ISSUE TITLE
Progress bar for sign-up process

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#19]
As a user, I want to be aware at all times of how far through the registration process I am, so that I am encouraged to keep going and not under the impression that I am in a never-ending process.

The client is interested in a wizard bar to show progress, particularly as many of the users will be suffering/will have suffered from depression & anxiety, and studies show that they are much less likely to carry on through the process and complete it if there is no end in sight

As a user, I want to be able to see how far I have progressed in my sign-up journey, and what I still need to do to complete my registration

**Comment by SimonLab** [comment]
@ellemindwave is the new UI will still have the progress bar? Qualtrics already have a progress bar that can be added directly from their platform. So do we want to display our own progress bar for the four main steps of the application: About- Consent - Qualtrics - Projects, or is the Qualtrics progress bar only the one needed?

**Comment by ellemindwave** [comment]
@SimonLab This is no longer needed, the client will just use the Qualtrics progress bar! Thank you :)
