### ISSUE TITLE
Notification email to user when saliva kit has been received

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#20]
As a user
I want to be alerted as to when my saliva sample has been received by the lab 

This is done manually by the lab into Redcap. 
A query can be run by the TTRR team periodically to then send an email to the users whose kits have been received.

**Comment by Cleop** [comment]
This morning we were informed during the meeting that LIMS automatically updates Redcap with this information.

**Comment by Cleop** [comment]
@ellemindwave, is this 2 separate issues/emails? 
One email for the received saliva sample and a separate one for complete registration? Or when you say registration is complete are you referring to the received saliva kit?

As some users may not opt in for the saliva sample kit and therefore their registration would be complete before any saliva kit interactions.

**Comment by ellemindwave** [comment]
@Cleop @sarahwelton Yes, you are probably right here. 

I will create another issue  (#31)

**Comment by Cleop** [comment]
So to clarify, this issue is now only to: 
create an email notification that is dispatched to a user when their saliva kit has been received.

This will be triggered by a checkbox in redcap that will be checked automatically through LIMS when they record having received a kit back.

**Comment by ellemindwave** [comment]
@Cleop Yes - all good.

**Comment by SimonLab** [comment]
Redcap doesn't automatically send notification to the application, so we need a way to check regularly the Redcap database to see which saliva kit has been received. We are thinking of different ways to implement this feature but we need a day of spike to determine definitely what is the best way to go. From there the implementation of the feature itself will be much easier.

**Comment by ellemindwave** [comment]
@SimonLab Just spoke to @sarahwelton about this as she is currently on a train. 
No spike is needed, the TTRR team can just run a query to see which saliva kits have been received back by the lab (the lab manually updates which ones are back) and then email the relevant people.

@sarahwelton will update more when she is back on wifi with her laptop

**Comment by ellemindwave** [comment]
@Cleop @SimonLab This email is no longer needed. 

The user will receive one email to let them know that their registration is complete. This is dealt with by #31 therefore I am closing this issue.
