### ISSUE TITLE
Phone number on the help box to be on one line

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#217]
It currently goes over two lines and would look better on one line

**Comment by Cleop** [comment]
@ellemindwave - do you have a screenshot for this? What screen size were you getting this at?

If my guess at what you're referring to is right, I can't see the number on two lines: 

<img src="https://cloud.githubusercontent.com/assets/16775804/25168960/46fca8ce-24dd-11e7-9935-755646e7dc32.png" width=180px />

**Comment by ellemindwave** [comment]
![screen shot 2017-04-19 at 10 05 13](https://cloud.githubusercontent.com/assets/26304634/25172055/c3a559fc-24e7-11e7-84e0-8256a0e8af1f.png)

**Comment by Cleop** [comment]
Thanks @ellemindwave - what device were you viewing it like this on? On what screen size? ie. had you made your browser smaller than normal?

**Comment by ellemindwave** [comment]
The phone number is always now on one line. Closing issue, thanks guys
