### ISSUE TITLE
Request a call back button is wider than the help box

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#218]
![screen shot 2017-04-18 at 17 28 42](https://cloud.githubusercontent.com/assets/26304634/25141763/7f2a6122-245c-11e7-80e6-533528c270d9.png)

**Comment by ellemindwave** [comment]
@SimonLab The button now remains smaller than the callback box at all times in the footer just about 👍 

The sign-up/log-in button at the top of the page isn't resizing correctly still though... 

![screen shot 2017-04-24 at 16 06 05](https://cloud.githubusercontent.com/assets/26304634/25343783/f43756e6-2907-11e7-81aa-ab7cfa82de7d.png)

**Comment by SimonLab** [comment]
![link-reduced](https://cloud.githubusercontent.com/assets/6057298/25353890/bc4aafa0-2928-11e7-9253-1760c98f2b27.png)
