### ISSUE TITLE
Content to be updated before user testing

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#219]
[Who We Are Page Links.docx](https://github.com/research-resource/research_resource/files/930425/Who.We.Are.Page.Links.docx)
[Title for Qualtrics Questionnaire.docx](https://github.com/research-resource/research_resource/files/930426/Title.for.Qualtrics.Questionnaire.docx)
[Information Sheet v9 180417 non-logged in user.docx](https://github.com/research-resource/research_resource/files/930427/Information.Sheet.v9.180417.non-logged.in.user.docx)
[Information Sheet v9 180417 logged in user.docx](https://github.com/research-resource/research_resource/files/930428/Information.Sheet.v9.180417.logged.in.user.docx)
[T&Cs v2 180417.docx](https://github.com/research-resource/research_resource/files/930429/T.Cs.v2.180417.docx)

**Comment by SimonLab** [comment]
@ellemindwave would it be possible to get a pdf version of the 2 information sheets if possible. I can create one from the files but the display of the content might be changed as I don't have Word. Thanks

**Comment by ellemindwave** [comment]
@SimonLab  Here is a PDF version from the team 

[Participant Information Sheet.pdf](https://github.com/research-resource/research_resource/files/951178/Participant.Information.Sheet.pdf)

**Comment by SimonLab** [comment]
Thanks @ellemindwave for the pdf, would it be possible to get the logged in version too? Thanks

**Comment by ellemindwave** [comment]
@SimonLab [Loggedinuser-TTRRinfosheet.pdf](https://github.com/research-resource/research_resource/files/951534/Loggedinuser-TTRRinfosheet.pdf)
