### ISSUE TITLE
Footer bugs

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#225]
@SimonLab 

Just noticed this happening on the footer of the about page... 

![screen shot 2017-04-21 at 13 57 52](https://cloud.githubusercontent.com/assets/26304634/25278514/265996c6-269b-11e7-8653-1642db5237d8.png)

**Comment by SimonLab** [comment]
Thanks @ellemindwave for spotting that, do you have more information about the display resolution where this is happening? I've just tried on my desktop and mobile but everything looks good.

**Comment by ellemindwave** [comment]
@SimonLab it is very strange indeed, it only seems to be happening on my computer...

**Comment by ellemindwave** [comment]
@SimonLab @Cleop Hopefully this will help? Still showing today, this was on Tom's computer

![image](https://cloud.githubusercontent.com/assets/26304634/25330038/15444c4a-28d6-11e7-9753-20c287543b31.png)

**Comment by ellemindwave** [comment]
<img width="565" alt="screen shot 2017-04-24 at 10 00 07" src="https://cloud.githubusercontent.com/assets/26304634/25331329/842b18ba-28da-11e7-8d4f-46bd1348bc4c.png">
<img width="657" alt="screen shot 2017-04-24 at 10 38 18" src="https://cloud.githubusercontent.com/assets/26304634/25331330/8431d13c-28da-11e7-9204-6f0b13f8721b.png">
<img width="610" alt="screen shot 2017-04-24 at 10 38 25" src="https://cloud.githubusercontent.com/assets/26304634/25331331/8434fb46-28da-11e7-8f5a-14e5351aae84.png">
<img width="625" alt="screen shot 2017-04-24 at 10 38 34" src="https://cloud.githubusercontent.com/assets/26304634/25331332/8438b222-28da-11e7-8966-1dbde1dc713c.png">
<img width="410" alt="screen shot 2017-04-24 at 10 38 54" src="https://cloud.githubusercontent.com/assets/26304634/25331334/843f3110-28da-11e7-8abd-9231675871c7.png">
<img width="402" alt="screen shot 2017-04-24 at 10 38 58" src="https://cloud.githubusercontent.com/assets/26304634/25331333/843d0d54-28da-11e7-8b9b-23e36d430dc0.png">
