### ISSUE TITLE
Photo for homepage

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#232]
@SimonLab  @iteles Please could this photo be inserted to see how it looks ahead of user testing?
I have a full version of the photo but it is too big to add here.. where would be useful for me to put it?

![270317-crf-101 edit](https://cloud.githubusercontent.com/assets/26304634/25394783/e8df5a3a-29d6-11e7-80f1-bbc0c90b96f1.jpg)

**Comment by SimonLab** [comment]
@ellemindwave the new picture is online, you might need to refresh the page or be sure the cache is refreshed.
