### ISSUE TITLE
Project page - Current/Upcoming projects module

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#25]
As a user, I want to see information on upcoming projects within the TTRR

**Comment by ellemindwave** [comment]
In time, when there are more projects, this would be two separate modules : Current projects and Upcoming projects. 

Initially however, there will relatively few projects, so these can all be on the same module "Current projects", otherwise the modules will look a little sparse

**Comment by ellemindwave** [comment]
http://7m7jfq.axshare.com/projects.html Link to relevant wireframe

**Comment by ellemindwave** [comment]
![screen shot 2017-03-17 at 14 53 21](https://cloud.githubusercontent.com/assets/26304634/24048711/9adf215e-0b21-11e7-8d53-284b2bcb6dfe.png)
![screen shot 2017-03-17 at 14 53 32](https://cloud.githubusercontent.com/assets/26304634/24048712/9ae3bc6e-0b21-11e7-94cf-841ec122357c.png)
![screen shot 2017-03-17 at 14 53 45](https://cloud.githubusercontent.com/assets/26304634/24048713/9ae763be-0b21-11e7-8a67-a5d1ec346df2.png)
![screen shot 2017-03-17 at 14 53 53](https://cloud.githubusercontent.com/assets/26304634/24048714/9aeeb9e8-0b21-11e7-98d2-20bd72f89493.png)

**Comment by Danwhy** [comment]
As with https://github.com/research-resource/research_resource/issues/13#issuecomment-287379566, time estimate is not including redcap integration

**Comment by ghost** [comment]
Pending the content pulling through from redcap this looks good, but @ellemindwave can you clarify your comment at the top - at the moment we have 3 sections Upcoming, current & archived.  Do you just want 2 sections for now?

**Comment by sarahwelton** [comment]
Yes, we only need 2 sections for now as there won't be many projects. They can come back to us at a later date if they need another section. So it will just be "Current projects" which will include both projects that are running, and projects that are in the pipeline.

**Comment by ellemindwave** [comment]
@Danwhy @Cleop Should I open another issue for merging current and upcoming project modules into one module?

**Comment by Cleop** [comment]
@ellemindwave Yes please! And if the original criteria of this issue have been met then please close 😄
