### ISSUE TITLE
Projects page - Archived projects module

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#26]
As a user, I want to see information on past projects that have been completed within the TTRR

As a user, I want to see archived projects that I have consented to that are now finished

As a user, I want to see projects that have finished within the TTRR, regardless of whether or not I have participated in them

As a user, I want to see archived projects that I have consented to and a brief update on the current status (nice to have)

**Comment by Cleop** [comment]
Relates #25 for wireframes

**Comment by Cleop** [comment]
Wireframes static page completed.

-Awaiting content (will create separate issue)
-Awaiting wireframe for individual archived project page and content (new issue).
