### ISSUE TITLE
Redcap Exploration Spike

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#29]
- Explore Redcap to become familiar with the API and documentation.
- Discover any potential blockers or limitations of using Redcap inline with the requirements of the project.

**Comment by Cleop** [comment]
Currently awaiting API key that @ellemindwave is sourcing before exploration can begin.

**Comment by ellemindwave** [comment]
RedCap tools - http://redcap-tools.github.io/projects/

**Comment by Danwhy** [comment]
Based on the api docs, it looks like the relevant methods to us are:

#### Export Instruments - https://kclplxredweb01.wis.kcl.ac.uk/api/help/?content=exp_instr
This is what we'll use to get the questions from redcap to display on the site

#### Import Records - https://kclplxredweb01.wis.kcl.ac.uk/api/help/?content=imp_records
This is what we'll use to send the user data into redcap

#### Export Records - https://kclplxredweb01.wis.kcl.ac.uk/api/help/?content=exp_reports
If we need to pull any of the user data from redcap, for example: to display user details, or check completion of an instrument

We're ready to test these as soon as the api token comes through

**Comment by ellemindwave** [comment]
@SimonLab @Cleop @Danwhy API Token is now here! Log in and you will have access in Redcap.
There is documentation in there too, to help getting started. 

In case of technical Redcap issues, Amos should be able to help.

**Comment by ellemindwave** [comment]
FYI this may need Alice/TTRR team to share the relevant project on Redcap - @sarahwelton will liaise with Alice if needs be about this
