### ISSUE TITLE
Qualtrics Exploration Spike

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#30]
- Once we have Qualtrics account information, explore Qualtrics platform and API
- Understand the documentation and means for using Qualtrics on the project.
- Discover any potential issues or blockers for using Qualtrics on the project.

**Comment by Cleop** [comment]
Currently awaiting account details being sourced by @ellemindwave before exploration can begin.

**Comment by ellemindwave** [comment]
Qualtrics: Lots of really helpful documentation and great user support

https://www.qualtrics.com/support/integrations/api-integration/api-integration/ 

https://api.qualtrics.com/

Their helpline is really good you just need to give them your account details- 02038 083 311

**Comment by ellemindwave** [comment]
@Cleop @SimonLab @Danwhy 

Account log-in details:
https://eu.qualtrics.com/ControlPanel/

You should now be able to log in and see the TTRR questionnaire on your projects page.

Let me know of any issues!

**Comment by SimonLab** [comment]
Thanks @ellemindwave we put the details in our shared Google Doc

**Comment by Danwhy** [comment]
@ellemindwave Apparently we don't have access to the api with this account:
<img width="461" alt="screen shot 2017-03-16 at 16 30 14" src="https://cloud.githubusercontent.com/assets/8939909/24007443/7874d85e-0a66-11e7-9120-de740f00021c.png">
Do you know who we'd have to ask to get it enabled?

**Comment by ellemindwave** [comment]
Hi @Danwhy - Alice has just gone in and changed something in your account and you should now be able to access the API?
Let me know if you're still having issues
Thanks

**Comment by Danwhy** [comment]
That's great, seems like it's enabled now, thanks
