### ISSUE TITLE
Projects Page - Projects I have consented to module

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#32]
As a user, I want to see projects that I am participating in so that I feel informed and in control of my sample

**Comment by Cleop** [comment]
- Check user's record on Redcap for participating projects
- Display projects dynamically on projects page when logged in

(Time estimates based on wireframe styling as UI not yet received)

**Comment by SimonLab** [comment]
- [x] Create Redcap project example form
- [x] Create function to load project from Redcap to the application
- [x] Save the users' consent project form in Redcap
