### ISSUE TITLE
Alerts on certain projects to show acceptance criteria

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#34]
As a user, I want to see upcoming projects that I am eligible to participate in, and if I am not eligible, I want to know why not, so that I don't feel excluded for no reason

**Comment by iteles** [comment]
@sarahwelton When we spoke to you about this on the very first day of the project (@ellemindwave had left for her meeting by then), you mentioned that this was no longer a requirement as for the first version of the application there will be so few projects that this feature will have little to no value. I hear you have also discussed this with the client.

Could you please confirm whether this is still a requirement?
If not, please feel free to close. Thanks! 😊

**Comment by sarahwelton** [comment]
Yes, can confirm this won't be needed. 

Eligibility criteria will be dealt with in the project content.
