### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by SimonLab** [research-resource/research_resource#4]
Add header with relevant section + add tachyons.io to the project

**Comment by Danwhy** [comment]
We wanted to use tachyons as an npm module, but there's apparently no support for npm css modules in brunch at the moment: https://github.com/brunch/brunch/issues/1473

We're going to use the CDN for now, and hopefully find a good way to instead have it as a dependency in the future

**Comment by iteles** [comment]
@SimonLab A screenshot of the header would also be good here 👍

**Comment by SimonLab** [comment]
![header-ttrr](https://cloud.githubusercontent.com/assets/6057298/23956972/0cd117fa-0996-11e7-8659-f8a52d4068dc.png)

We can still use tachyons with npm, the trick is to use the [postinstall function](https://docs.npmjs.com/misc/scripts) of npm to create a copy of tachyons.min.css into the web/static/css folder. This file will normaly be compiled automatically into app.css by brunch

**Comment by SimonLab** [comment]
done with #28
