### ISSUE TITLE
Notification to TTRR team when someone requests a saliva kit

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#49]
As an admin, I want to be notified when someone requests a saliva kit, so that I can put one together and send it to them for completion

**Comment by Cleop** [comment]
- Notification by email upon completion of the saliva consent form process.

**Comment by ellemindwave** [comment]
Linked to new issue #124 . When the alert shows on the page to the user 'Thank you for requesting your saliva sample kit... ', then this triggers an email to the TTRR team to let them know someone has requested a saliva sample kit

**Comment by Danwhy** [comment]
The email is currently sent to tt.research.resource@gmail.com, but this can easily be switched out

**Comment by ellemindwave** [comment]
@Danwhy thanks for this - I trust that it works but as I don't have access to the inbox of that email address (nor do I know whether or not it exists yet) I can't really test it and close the issue.

If it is easy to switch it out, is it maybe possible for it to be replaced an email address we can access so that we can test it? or can you screenshot one of the emails that comes through?

Thanks!

**Comment by Danwhy** [comment]
These are the emails that came through:
<img width="663" alt="screen shot 2017-04-05 at 11 30 12" src="https://cloud.githubusercontent.com/assets/8939909/24701690/58ce76d0-19f3-11e7-93a1-2a02e112c862.png">
<img width="724" alt="screen shot 2017-04-05 at 11 30 01" src="https://cloud.githubusercontent.com/assets/8939909/24701696/5c133ede-19f3-11e7-8747-cf1270356fba.png">

**Comment by ellemindwave** [comment]
Ha - as you can see, my creativity didn't last long 😂 

Great! closing this issue 👍
