### ISSUE TITLE
'Home' page

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#5]
As a user
I want to quickly and simply find out what the core purpose of the Research Resource is and whether signing up is of interest to me

**Comment by Cleop** [comment]
This is the wireframe for the home page:

![image](https://cloud.githubusercontent.com/assets/16775804/24036825/4de8ac04-0af3-11e7-8b31-0d9a6fb840b2.png)
![image](https://cloud.githubusercontent.com/assets/16775804/24036852/6531bbbc-0af3-11e7-9224-4722e9befb4c.png)
![image](https://cloud.githubusercontent.com/assets/16775804/24036864/71b61658-0af3-11e7-9408-caa0a696465d.png)

**Comment by ghost** [comment]
Compared to the wireframe above the sign up bar along the bottom is missing:
https://www.dropbox.com/s/11zzv6g77hfvmld/Screenshot%202017-03-24%2010.14.11.png?dl=0

**Comment by ghost** [comment]
Otherwise it's all looking good to me.

**Comment by Danwhy** [comment]
Thanks @katyedwards, I've added that in to all relevant pages now

**Comment by ghost** [comment]
@danwhy has this been merged because I'm not seeing the update with the footer?

**Comment by Danwhy** [comment]
@katyedwards The latest version has been deployed now, so you should be able to see it. You may have to go to 'my account' and log out though, as the signup footer won't show up if you're logged in

**Comment by ghost** [comment]
Thanks @Danwhy

**Comment by sarahwelton** [comment]
Hey guys - I know this issue is closed (should I open a new one?) Having spoken with Thalia, she has decided she doesn't want the sign up information on this page - so as per http://k2sf3e.axshare.com/#g=1&p=home

Can we just delete that piece of content @Cleop

**Comment by SimonLab** [comment]
@sarahwelton the signup infomation has been removed with the PR #83, let us know if this issue can be closed, thanks

**Comment by ellemindwave** [comment]
Thanks guys, this can be closed 👍
