### ISSUE TITLE
Notification to let Redcap know that Saliva kit has been received by lab

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#50]
As an admin, I want to be notified when a saliva sample has been received by the lab, so that I can update the user’s record in Redcap

It was confirmed that is done by LIMS (lab) to Redcap automatically

**Comment by Cleop** [comment]
@ellemindwave - To clarify, is the purpose of this issue for the team to create an email notification to admins when LIMS updates the patient record on Redcap (which is done automatically)?

I wanted to clarify what you meant when you said ' **It** was confirmed that is done by LIMS (lab) to Redcap automatically', to check what you were referring to by **'it'**.

**Comment by ellemindwave** [comment]
This is done manually by the TTRR team, so I am closing the issue
