### ISSUE TITLE
'About the sign up process' page

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#6]
As a user 
I want to find out what the process of signing up to the Research Resource is, how difficult it is, what information I need to provide, and how long it will take me so that I can decide if and when I want to sign up

**Comment by iteles** [comment]
@ellemindwave the 'so that' portion of the user story above is missing - always good to understand the user's motivations as it often changes priorities :blush:

**Comment by Cleop** [comment]
![image](https://cloud.githubusercontent.com/assets/16775804/24036901/9d602618-0af3-11e7-96e4-9a7996f866ed.png)

Continued (the side element with request callback is not separate to the 'best time to call' box):
![image](https://cloud.githubusercontent.com/assets/16775804/24036936/bdab5b7c-0af3-11e7-8c8d-a37d49690697.png)

**Comment by Cleop** [comment]
The text continues (copy can be found on the complete wireframes doc)
At the end of the copy it then should look like this:
![image](https://cloud.githubusercontent.com/assets/16775804/24037000/061295ba-0af4-11e7-9fff-a12e2c288e9e.png)

**Comment by ghost** [comment]
Looks good thanks!
