### ISSUE TITLE
How to receive event when Qualtrics survey is completed

### ISSUE THREAD

**Issue by SimonLab** [research-resource/research_resource#66]
We are using iframe to display the Qualtrics questionnaire (see #53) so when a survey is completed we want the user to be redirected to the next page (/projects).

- Display a link at the bottom of the page where the user can click to see the projects (quick and easy)
- Get notification from Qualtrics (https://api.qualtrics.com/docs/events), we will still have to find a way to redirect automatically the user (websocket?)
- Create a special link on the survey which redirect to the /project endpoints

@Danwhy do you have any other thoughts on how we can do this?

**Comment by Danwhy** [comment]
I think that when the user reaches the final page of the survey, that tells them the survey is complete, we should have a 'continue'/'next' button underneath the iframe, just as we would if the survey was on our own site

**Comment by SimonLab** [comment]
We can define a custom message and the end of the questionnaire:
![survey-end-message](https://cloud.githubusercontent.com/assets/6057298/24200314/b3f3e904-0f04-11e7-95fb-a6ce17b74385.png)

This message can contains a link to the next page (projects). We just need to define the taget property of the link to "_top" to redirect the main page and not just the iframe
![survey-message](https://cloud.githubusercontent.com/assets/6057298/24200357/d6e97a96-0f04-11e7-9f25-ad627b0ea944.png)

An options also exist to automatically send an email from Qualtrics to the user when the survey is finished.

**Comment by SimonLab** [comment]
This issue is resolved by displaying a custom message at the end of the questionnaire with a link to the projects page
