### ISSUE TITLE
FAQs page

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#7]
This will be satisfied by About page / FAQs / Consent Information sheet

As a user
I want to find out what the consequences of signing up will be - how often will I have to provide information? How often will I be contacted? Who will have access to my data? so that I can make an informed decision as to whether I want to sign up or not

This page will have all the FAQ content on it, with concertinas to expand and retract with the individual questions/answers

**Comment by sarahwelton** [comment]
so that I can make an informed decision as to whether I want to sign up or not

**Comment by ellemindwave** [comment]
![screen shot 2017-03-17 at 14 56 56](https://cloud.githubusercontent.com/assets/26304634/24048850/10b98d1a-0b22-11e7-92aa-2d1bac575bcb.png)
![screen shot 2017-03-17 at 14 57 05](https://cloud.githubusercontent.com/assets/26304634/24048851/10ba9caa-0b22-11e7-8bdb-ae3a549a2278.png)

**Comment by ghost** [comment]
Page looks good but awaiting content

**Comment by Cleop** [comment]
Will close this issue for page creation and create new issue for content as new issue.
