### ISSUE TITLE
Fix error page for signing up with same email address

### ISSUE THREAD

**Issue by katbow** [research-resource/research_resource#73]
I had [this issue](https://github.com/healthlocker/healthlocker/issues/336) posted on healthlocker which I think is for you folks 🙂 . 

Looks like you have [`debug_errors: true`](https://github.com/research-resource/research_resource/blob/master/config/prod.exs#L19) for production environment. You can remove that line completely and pages like that will show up as 404/500 instead 👍 .

**Comment by katbow** [comment]
Also to fix the error so it doesn't even go to an error page, you can set [email as a `unique_constraint`](https://hexdocs.pm/ecto/Ecto.Changeset.html#unique_constraint/3) in your [changeset](https://github.com/research-resource/research_resource/blob/master/web/models/user.ex#L15-L19). That should prevent it from even trying to insert into the db, and you can instead return errors on the signup form.

P.S. sorry can't add labels!

**Comment by SimonLab** [comment]
resolved with #91

**Comment by katbow** [comment]
Sweet 👍  😄
