### ISSUE TITLE
'Who we are' page

### ISSUE THREAD

**Issue by ellemindwave** [research-resource/research_resource#8]
As a user
I want to see who is running the Research Resource project and find out more about them, so that I can be sure my sample is going to a worthwhile and safe project

**Comment by ellemindwave** [comment]
![screen shot 2017-03-17 at 14 55 24](https://cloud.githubusercontent.com/assets/26304634/24048793/df998c94-0b21-11e7-8e84-21da6edf788f.png)
![screen shot 2017-03-17 at 14 55 34](https://cloud.githubusercontent.com/assets/26304634/24048794/df9fc71c-0b21-11e7-8bdc-035f8752eacf.png)
![screen shot 2017-03-17 at 14 55 45](https://cloud.githubusercontent.com/assets/26304634/24048795/dfa83fb4-0b21-11e7-8b59-40264676c97c.png)

**Comment by ghost** [comment]
Page looks good but awaiting content

**Comment by ghost** [comment]
Content to be added...
[Who we are version 3 220317.docx](https://github.com/research-resource/research_resource/files/868222/Who.we.are.version.3.220317.docx)

**Comment by Cleop** [comment]
Will close this issue and create a new issue for content relating to this issue.
