### ISSUE TITLE
Card details required for email notifications using AWS SES

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#84]
In order to send email notifications we need to use a service that enables us to do this. dwyl advocates using Amazon Web Services Simple Email Service ("AWS SES") for reliably sending email messages. 

The key reasons we choose AWS SES are because it has good documentation, excellent "deliverability" and no minimum spend (10 cents per 1000 emails sent)! There's also a generous "Free Tier" of 65k emails per month if you're new to AWS.

You can learn more about it on our README: github.com/dwyl/sendemail

In order to register for an AWS SES account you must provide some card details (regardless of whether you reach a quantity of emails that incurs a charge). @ellemindwave please can you discuss  this with the client and provide us with the necessary details?

**Comment by ellemindwave** [comment]
@Cleop Have discussed this with the client - she is fine to give card details for this. Elle will get them and share asap

**Comment by ellemindwave** [comment]
@Cleop The relevant member of the team is on holiday for a few weeks, and the client is trying to get another in the team's card.. 
Is it possible to add in Alice's card details now, and change them further down the line so that this doesn't hold things up any longer?

**Comment by ellemindwave** [comment]
@Cleop has the card details 👍
