### ISSUE TITLE
Contact Us: wireframe/ extra info needed

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#98]
There's a `Contact Us` link in the footer of the main wireframes but we've not yet got any more indication as to what this should lead to. 

@ellemindwave @sarahwelton please can we have a wireframe and an indication of what kind of contact this is for users to make? Ie. listing a phone number or enabling them to send emails via a form? According to which you're talking about then this will alter the time/complexity it takes to produce this.

**Comment by ellemindwave** [comment]
@sarahwelton @Cleop 
The 'Contact us' link in the footer should lead to a page which contains the following:

- Request for callback (which sends an email to the TTRR team) email address will probably be ttrr@kcl.ac.uk but this is awaiting confirmation by the Kings IT team
- Email form
- Free phone number for them to call us

Wireframe for this page to come from @sarahwelton

**Comment by sarahwelton** [comment]
![contact_us](https://cloud.githubusercontent.com/assets/26305143/24588684/31a05716-17c5-11e7-9dd4-e49a05f9b919.png)
