### ISSUE TITLE
Create mobile/responsive site versions

### ISSUE THREAD

**Issue by Cleop** [research-resource/research_resource#99]
So far the wireframes and direction of the project has been focussing on desktop use. 

Has the client discussed mobile design/ responsiveness? Do you have any wireframes for this? Or is this not a priority for the purpose of the site? 

@ellemindwave @sarahwelton

**Comment by ellemindwave** [comment]
@Cleop Yes, it needs to be mobile responsive. We had assumed that this is fairly standard procedure - can provide mobile wireframes if required? 👍

**Comment by Cleop** [comment]
@ellemindwave Okay, thanks for clarifying. Yes please for wireframes.

**Comment by ellemindwave** [comment]
@sarahwelton's domain :) When you get the chance please, Sarah!

**Comment by iteles** [comment]
@ellemindwave To clarify, you're absolutely right that 'mobile first' *is* our standard procedure - it is very much our preference to start simple and go from mobile to desktop. However, given the directive in [this issue](https://github.com/research-resource/research_resource/issues/23) that we only wanted to cater for desktop, the fact that we have only been given desktop wireframes and the time limitations you are facing with the client, we created the desktop versions first so you would have something to show at your demo on Tuesday.

That's why we wanted to raise this question quite explicitly to make sure we were all on the same page, sounds like we are now 👍

**Comment by sarahwelton** [comment]
@cleop do you need wireframes for every single page? I'm hoping that most of it is common sense so I won't need to draw it all out. Is there a particular page or element you'd like me to focus on?

**Comment by sarahwelton** [comment]
![rr_homepage_mobile](https://cloud.githubusercontent.com/assets/26305143/24587832/4bd9cc08-17b5-11e7-9a47-18431e7247cc.jpg)

HOMEPAGE MOBILE WIREFRAME

Hope you can see this clearly! Phone camera quality isn't great. It's quicker for me to draw stuff out like this, but understand it could be less clear, so shout if you need any clarification. 

@indiamindwave24 a couple of bits here for you to design up - burger menu mostly. (Also, we need to decide whether to show hero image on mobile.)

**Comment by sarahwelton** [comment]
![rr_about_mobile](https://cloud.githubusercontent.com/assets/26305143/24587892/630af2f2-17b6-11e7-95a9-35bbbcf95fe9.jpg)

ABOUT PAGE MOBILE WIREFRAME

**Comment by iteles** [comment]
@sarahwelton It would be good to have any particular user patterns you want us to stick to, e.g. when there is a contact/withdrawal/sign up module in a column to the right of the main content, where on the page do you want us to put it - under the main content? But if you're happy for us to go ahead and put the rest together by trying to extrapolate from what we have, we can do that 👍

**Comment by sarahwelton** [comment]
Notes:
Stack elements to one column
Sign up CTA at the top of each page sits under the standfirst/
Additional modules (on right hand side) should sit under main content.

**Comment by sarahwelton** [comment]
Thanks @iteles  - if there is anything specific, give me a shout. I'll continue to try and add pages as and when I get time :)

**Comment by Cleop** [comment]
@sarahwelton thanks for what you've managed to get done here. 

Just for context - has the client seen any mobile wireframes/ UI? It sounds like you want us to largely self-determine the mobile look but I just wanted to make sure that we're not going to conflict anything that's already been shown to the client?

**Comment by sarahwelton** [comment]
@cleop no, the client hasn't seen anything. We've explained to them that basic principles though, eg 3 columns stack to 1 column on smaller screens.

**Comment by Cleop** [comment]
Still to be implemented for mobile responsiveness:

- [x] Home page
- [x] Who we are
- [x] Projects Page
- [x] FAQs
- [x] Resources
- [x] My Account
- [x] Ts and Cs
- [x] Consent
- [x] Individual Project Consent
- [ ]  Burger Menu design from @indiamindwave24 
- [x]  Login Page

**Comment by sarahwelton** [comment]
@indiamindwave24

**Comment by ellemindwave** [comment]
I have tested this on mobile and it looks good - want to run it by @indiamindwave24 too just incase I have missed anything 😀

**Comment by Danwhy** [comment]
:+1: We've found a few small issues displaying on an iphone 5 that we'll try to fix, but do let us know if there's anything else you find
